import re
import codecs

path = r'c:\Users\PC\.gemini\antigravity\scratch\ulc_club_website\index-template.html'
with codecs.open(path, 'r', 'utf-8') as f:
    base = f.read()

# Translations array:
locales = [
    {
        "file": "index.html",
        "lang_code": "en",
        "lang_name": "English",
        "map": {
            "ULC Professionals Club | 跨国商务人士成长": "ULC Professionals Club | Growth for Professionals",
            "专为跨国商务人士打造的成长型课程项目。这是一次对自己成长的投资，对自己视野的拓展。": "A growth-oriented course program designed for transnational professionals. It's an investment in your growth and an expansion of your horizons.",
            "核心优势": "Core Advantages",
            "课程详情": "Course Details",
            "适合人群": "Target Audience",
            "立即报名": "Sign Up",
            "这是一次对自己成长的投资，这是一次对自己视野的拓展": "An investment in your growth, an expansion of your horizons",
            "专为跨国商务人士打造的 ": "A ",
            " 课程项目": " Program for Professionals",
            "这不只是英语学习，更是一个帮助你走进真实新加坡商务与社交圈的成长机会。": "More than just English learning, it's an opportunity to step into real Singapore business and social circles.",
            "个月时长": "Months Duration",
            "次精品课程": "Premium Sessions",
            "真实社交融入": "Real Social Integration",
            "了解详情及费用": "Learn More & Pricing",
            "课程核心优势": "Core Course Advantages",
            "独创的教学与实战结合模式，助你全方位提升跨国商务能力。": "An original model combining teaching and practical application to comprehensively elevate your transnational business skills.",
            "沉浸式商业场域": "Immersive Business Environment",
            "在3个月、20次的多国家学员学习互动中，精准模拟真实商务与社交环境，让成长在实战中自然发生。(Immersive Practice)": "Through 3 months and 20 sessions with multinational students, we simulate real business and social environments, allowing natural growth. (Immersive Practice)",
            "结果导向型交付": "Result-Oriented Delivery",
            "坚持“每课必有产出”。通过可视化的成果转换 (Visible Output)，确保从理论输入到实操运用的无缝衔接。(Result-Oriented Delivery)": "We insist on 'visible output for every lesson', ensuring a seamless transition from theoretical input to practical application. (Result-Oriented Delivery)",
            "深度本地化解码": "Deep Local Integration",
            "专为非母语人士定制。不仅是语言的进阶，更是对新加坡规则与社交逻辑的深度拆解，助你跨越文化隔阂。(Deep Local Integration)": "Customized for non-native speakers. A deep breakdown of Singapore's rules and social logic to cross cultural barriers. (Deep Local Integration)",
            "跨文化深度链接": "Cross-Cultural Connection",
            "在多国背景的圈层中，建立能够共鸣、互信的高质量商业人脉网络，拓展国际化视野。(Cross-Cultural Connection)": "Build a high-quality, trustworthy business network in a multinational circle, expanding your international perspective. (Cross-Cultural Connection)",
            "开课时间：": "Start Date:",
            "2026年4月21日 - 6月25日": "Apr 21 - Jun 25, 2026",
            "上课频次：": "Frequency:",
            "每周二、周四上课 (晚上 7:00 - 9:00)": "Every Tue & Thu (7:00 PM - 9:00 PM)",
            "课程总量：": "Total Sessions:",
            "共 20 节课程": "20 Sessions",
            "教学模式：": "Teaching Mode:",
            "以讨论式教学为主，结合真实场景与引导式交流": "Discussion-based teaching, combined with real scenarios and guided communication.",
            "三个月进阶路径清晰": "Clear 3-Month Progression Path",
            "个人成长数字档案": "Digital Growth Profile",
            "商业实战挑战赛": "Real Business Challenge",
            "模块化技能产出": "Modular Skill Output",
            "菁英结业荣誉包": "Elite Graduation Kit",
            "关键收获": "Key Outcomes",
            "三个月后，你将实现蜕变": "In 3 months, you will transform.",
            "英文表达重塑": "English Expression Reshaped",
            "彻底克服心理障碍，实现从恐惧开口到“流利开口”的转变。(Confidence)": "Overcome psychological barriers and transition from fear of speaking to fluent communication. (Confidence)",
            "行动转化": "Action Conversion",
            "学会不仅在现场聊得来，更能持续维系高价值关系。(Action)": "Learn to consistently maintain high-value relationships. (Action)",
            "顺畅融入": "Smooth Integration",
            "掌握狮城沟通底色，实现文化丝滑嵌入，本地游刃有余。(Integration)": "Master communication fundamentals in Singapore for seamless cultural integration. (Integration)",
            "归属共鸣": "Sense of Belonging",
            "加入志同道合全球社群，拥有长期的支持系统。(Belonging)": "Join a global community of like-minded individuals with long-term support. (Belonging)",
            "课程适合谁？": "Target Audience?",
            "五大基础场景 (初级)": "5 Basic Scenarios",
            "五大进阶场景 (中级)": "5 Advanced Scenarios",
            "会议沟通不顺畅，难以清晰表达观点": "Unsmooth meeting communication, struggling to clearly express viewpoints.",
            "邮件写作不够专业，影响职场形象": "Unprofessional email writing affecting workplace image.",
            "面对电话沟通时缺乏信心": "Lack of confidence when communicating over the phone.",
            "在社交聚会中不知如何自然展开对话": "Not knowing how to naturally start conversations in social gatherings.",
            "演讲与汇报表现单一，缺乏吸引力": "Monotonous speeches and presentations lacking appeal.",
            "跨文化交流中容易产生沟通误差": "Easy to have communication errors in cross-cultural exchanges.",
            "商务谈判中的表达力度与说服力不足": "Lack of expressive power and persuasiveness in business negotiations.",
            "团队合作场景下的沟通协同有待提升": "Communication and collaboration in teamwork scenarios need improvement.",
            "品牌叙事与价值传达能力较弱": "Weak brand storytelling and value communication skills.",
            "正式商务场合中的回应不够准确得体": "Inaccurate or inappropriate responses in formal business settings.",
            "不止于课堂": "Beyond the Classroom",
            "除了商务课程，我们每月还会安排": "Besides business courses, we arrange",
            " 场精选活动": " curated events every month",
            "行业分享会": "Industry Sharing Sessions",
            "本地专业人士为您带来一手的行业洞察。": "Local professionals bring you firsthand industry insights.",
            "商务社交与人脉拓展": "Business Networking",
            "轻松愉悦的环境中结识更多商业伙伴。": "Meet more business partners in a relaxed and pleasant environment.",
            "真实场景体验": "Real Scenario Experience",
            "走进新加坡真实商业与社交场景，提升实际沟通能力。": "Step into real business and social scenarios in Singapore to enhance practical communication skills.",
            "准备好开启您的成长之旅了吗？": "Ready to Start Your Growth Journey?",
            "抓住在这个多元且国际化的商业环境中脱颖惊而出的机会。": "Seize the opportunity to stand out in this diverse and international business environment.",
            "抓住在这个多元且国际化的商业环境中脱颖而出的机会。": "Seize the opportunity to stand out in this diverse and international business environment.",
            "课程费用": "Course Fee",
            "时长：3个月 (20次精品课)": "Duration: 3 Months (20 Premium Sessions)",
            "报名咨询 / 立即加入": "Consultation / Join Now",
            "United Language Centre": "United Language Centre",
            "成长型": "Growth-Oriented"
        }
    },
    {
        "file": "index-ko.html",
        "lang_code": "ko",
        "lang_name": "한국어",
        "map": {
            "ULC Professionals Club | 跨国商务人士成长": "ULC 프로페셔널 클럽 | 글로벌 비즈니스 전문가 성장",
            "专为跨国商务人士打造的成长型课程项目。这是一次对自己成长的投资，对自己视野的拓展。": "글로벌 비즈니스 전문가를 위해 설계된 성장 지향적 코스입니다. 당신의 성장과 시야 확장을 위한 투자입니다.",
            "核心优势": "핵심 강점",
            "课程详情": "코스 세부 정보",
            "适合人群": "코스 대상",
            "立即报名": "지금 등록하기",
            "这是一次对自己成长的投资，这是一次对自己视野的拓展": "당신의 성장을 위한 투자, 시야를 넓히는 기회입니다",
            "专为跨国商务人士打造的 ": "글로벌 비즈니스 전문가를 위한 ",
            " 课程项目": " 프로그램",
            "这不只是英语学习，更是一个帮助你走进真实新加坡商务与社交圈的成长机会。": "단순한 영어 학습을 넘어, 싱가포르의 실제 비즈니스 및 소셜 네트워크로 진입할 수 있는 기회입니다.",
            "个月时长": "개월 진행",
            "次精品课程": "프리미엄 세션",
            "真实社交融入": "실제 소셜 통합",
            "了解详情及费用": "상세 정보 및 비용",
            "课程核心优势": "코스 핵심 강점",
            "独创的教学与实战结合模式，助你全方位提升跨国商务能力。": "티칭과 실무가 결합된 독창적인 모델로 글로벌 비즈니스 역량을 전방위로 향상시킵니다.",
            "沉浸式商业场域": "몰입형 비즈니스 환경",
            "在3个月、20次的多国家学员学习互动中，精准模拟真实商务与社交环境，让成长在实战中自然发生。(Immersive Practice)": "다국적 수강생들과의 상호작용을 통해 실제 비즈니스 환경을 완벽하게 시뮬레이션합니다. (Immersive Practice)",
            "结果导向型交付": "결과 지향적 딜리버리",
            "坚持“每课必有产出”。通过可视化的成果转换 (Visible Output)，确保从理论输入到实操运用的无缝衔接。(Result-Oriented Delivery)": "이론에서 실무 적용까지 원활하게 이어지는 '눈에 보이는 결과물'을 지향합니다. (Result-Oriented Delivery)",
            "深度本地化解码": "심층적인 현지화 해석",
            "专为非母语人士定制。不仅是语言的进阶，更是对新加坡规则与社交逻辑的深度拆解，助你跨越文化隔阂。(Deep Local Integration)": "비원어민 맞춤형으로, 언어 발전을 넘어 싱가포르의 문화적 장벽을 넘도록 돕습니다. (Deep Local Integration)",
            "跨文化深度链接": "문화 간 심층 네트워킹",
            "在多国背景的圈层中，建立能够共鸣、互信的高质量商业人脉网络，拓展国际化视野。(Cross-Cultural Connection)": "다국적 그룹 내에서 신뢰할 수 있는 고품질 비즈니스 인맥을 구축하고 국제적 시야를 넓힙니다. (Cross-Cultural Connection)",
            "开课时间：": "시작일:",
            "2026年4月21日 - 6月25日": "2026년 4월 21일 - 6월 25일",
            "上课频次：": "수업 시간:",
            "每周二、周四上课 (晚上 7:00 - 9:00)": "매주 화/목 (오후 7:00 - 9:00)",
            "课程总量：": "총 수업:",
            "共 20 节课程": "총 20회",
            "教学模式：": "수업 방식:",
            "以讨论式教学为主，结合真实场景与引导式交流": "토론식 수업 위주, 실제 상황 및 가이드된 커뮤니케이션 결합.",
            "三个月进阶路径清晰": "명확한 3개월 성장 경로",
            "个人成长数字档案": "개인 성장 디지털 프로필",
            "商业实战挑战赛": "실전 비즈니스 챌린지",
            "模块化技能产出": "모듈식 스킬 아웃풋",
            "菁英结业荣誉包": "엘리트 졸업 키트",
            "关键收获": "주요 성과",
            "三个月后，你将实现蜕变": "3개월 후, 당신의 큰 변화를 기대하세요.",
            "英文表达重塑": "영어 표현 재구성",
            "彻底克服心理障碍，实现从恐惧开口到“流利开口”的转变。(Confidence)": "심리적 장벽을 완전히 극복하고 '유창한 소통'으로 전환합니다. (Confidence)",
            "行动转化": "행동 전환",
            "学会不仅在现场聊得来，更能持续维系高价值关系。(Action)": "고가치의 관계를 지속적으로 유지하는 법을 배웁니다. (Action)",
            "顺畅融入": "원활한 통합",
            "掌握狮城沟通底色，实现文化丝滑嵌入，本地游刃有余。(Integration)": "싱가포르 소통의 기본을 마스터하여 문화에 자연스럽게 녹아듭니다. (Integration)",
            "归属共鸣": "소속감과 공감",
            "加入志同道合全球社群，拥有长期的支持系统。(Belonging)": "뜻을 같이하는 글로벌 커뮤니티에 합류하여 장기적인 지원 시스템을 갖춥니다. (Belonging)",
            "课程适合谁？": "어떤 분들에게 적합한가요?",
            "五大基础场景 (初级)": "5대 기본 시나리오",
            "五大进阶场景 (中级)": "5대 심화 시나리오",
            "会议沟通不顺畅，难以清晰表达观点": "회의 소통이 원활하지 않고 논점을 명확히 표현하기 어렵다.",
            "邮件写作不够专业，影响职场形象": "이메일 작성이 전문적이지 않아 직장 내 이미지에 영향을 미친다.",
            "面对电话沟通时缺乏信心": "전화 통화 시 자신감이 부족하다.",
            "在社交聚会中不知如何自然展开对话": "소셜 모임에서 자연스럽게 대화하는 법을 모른다.",
            "演讲与汇报表现单一，缺乏吸引力": "프레젠테이션 및 보고 능력이 단조롭고 매력이 부족하다.",
            "跨文化交流中容易产生沟通误差": "문화 간 교류에서 소통 오류가 발생하기 쉽다.",
            "商务谈判中的表达力度与说服力不足": "비즈니스 협상에서 표현력과 설득력이 부족하다.",
            "团队合作场景下的沟通协同有待提升": "팀워크 상황에서 협업 및 소통 능력을 향상시킬 필요가 있다.",
            "品牌叙事与价值传达能力较弱": "브랜드 스토리텔링 및 가치 전달 능력이 약하다.",
            "正式商务场合中的回应不够准确得体": "격식을 갖춘 비즈니스 자리에서 대응이 적절하지 않다.",
            "不止于课堂": "교실을 넘어서",
            "除了商务课程，我们每月还会安排": "비즈니스 코스 외에도 매월",
            " 场精选活动": "개의 특별 이벤트를 제공합니다:",
            "行业分享会": "업계 공유회",
            "本地专业人士为您带来一手的行业洞察。": "현지 전문가들이 생생한 업계 인사이트를 제공합니다.",
            "商务社交与人脉拓展": "비즈니스 네트워킹",
            "轻松愉悦的环境中结识更多商业伙伴。": "편안하고 즐거운 분위기에서 더 많은 비즈니스 파트너를 만나보세요.",
            "真实场景体验": "실제 상황 체험",
            "走进新加坡真实商业与社交场景，提升实际沟通能力。": "싱가포르의 실제 비즈니스 및 소셜 상황에 참여하여 실전 소통 능력을 높입니다.",
            "准备好开启您的成长之旅了吗？": "성장 여정을 시작할 준비가 되셨나요?",
            "抓住在这个多元且国际化的商业环境中脱颖而出的机会。": "이 다양하고 국제적인 비즈니스 환경에서 눈에 띄는 기회를 잡으세요.",
            "课程费用": "코스 비용",
            "时长：3个月 (20次精品课)": "기간: 3개월 (20회 프리미엄 수업)",
            "报名咨询 / 立即加入": "상담 및 가입하기",
            "成长型": "성장형"
        }
    },
    {
        "file": "index-ja.html",
        "lang_code": "ja",
        "lang_name": "日本語",
        "map": {
            "ULC Professionals Club | 跨国商务人士成长": "ULCプロフェッショナルクラブ | グローバルビジネスの成長",
            "专为跨国商务人士打造的成长型课程项目。这是一次对自己成长的投资，对自己视野的拓展。": "グローバルビジネスのプロ向けに設計された成長重視のコースプログラムです。あなたの成長と視野の拡大への投資です。",
            "核心优势": "コアの強み",
            "课程详情": "コース詳細",
            "适合人群": "対象者",
            "立即报名": "申し込む",
            "这是一次对自己成长的投资，这是一次对自己视野的拓展": "これはあなたの成長への投資であり、視野を広げる機会です",
            "专为跨国商务人士打造的 ": "ビジネスパーソンのための",
            " 课程项目": "・プログラム",
            "这不只是英语学习，更是一个帮助你走进真实新加坡商务与社交圈的成长机会。": "単なる英語学習ではなく、シンガポールのリアルなビジネスや社交界に足を踏み入れるための成長機会です。",
            "个月时长": "ヶ月",
            "次精品课程": "回のセッション",
            "真实社交融入": "リアルなソーシャル統合",
            "了解详情及费用": "詳細と料金を確認",
            "课程核心优势": "コアの強み",
            "独创的教学与实战结合模式，助你全方位提升跨国商务能力。": "教育と実践を組み合わせた独自のモデルで、グローバルビジネススキルを全面的に向上させます。",
            "沉浸式商业场域": "没入型ビジネス環境",
            "在3个月、20次的多国家学员学习互动中，精准模拟真实商务与社交环境，让成长在实战中自然发生。(Immersive Practice)": "多国籍受講生とのインタラクションを通じ、実際の環境を体験します。(Immersive Practice)",
            "结果导向型交付": "結果重視のデリバリー",
            "坚持“每课必有产出”。通过可视化的成果转换 (Visible Output)，确保从理论输入到实操运用的无缝衔接。(Result-Oriented Delivery)": "「毎授業のアウトプット」にこだわり、理論からのスムーズな移行を保証します。(Result-Oriented Delivery)",
            "深度本地化解码": "深いローカライズ解読",
            "专为非母语人士定制。不仅是语言的进阶，更是对新加坡规则与社交逻辑的深度拆解，助你跨越文化隔阂。(Deep Local Integration)": "非ネイティブ向けにカスタマイズされ、シンガポールのルールを深く分解します。(Deep Local Integration)",
            "跨文化深度链接": "異文化ディープネットワーキング",
            "在多国背景的圈层中，建立能够共鸣、互信的高质量商业人脉网络，拓展国际化视野。(Cross-Cultural Connection)": "共感と信頼に基づく質の高いビジネスネットワークを構築します。(Cross-Cultural Connection)",
            "开课时间：": "開始日:",
            "2026年4月21日 - 6月25日": "2026年4月21日 - 6月25日",
            "上课频次：": "頻度:",
            "每周二、周四上课 (晚上 7:00 - 9:00)": "毎週火・木 (午後7:00 - 9:00)",
            "课程总量：": "総セッション数:",
            "共 20 节课程": "全20回",
            "教学模式：": "指導スタイル:",
            "以讨论式教学为主，结合真实场景与引导式交流": "ディスカッション主体の教育、実際のシナリオとガイド付き対話。",
            "三个月进阶路径清晰": "明確な3ヶ月の成長パス",
            "个人成长数字档案": "個人の成長デジタルプロファイル",
            "商业实战挑战赛": "実践ビジネスチャレンジ",
            "模块化技能产出": "モジュール型スキルアウトプット",
            "菁英结业荣誉包": "エリート卒業キット",
            "关键收获": "主要な成果",
            "三个月后，你将实现蜕变": "3ヶ月後、あなたは大きな変化を実現します。",
            "英文表达重塑": "英語表現の再構築",
            "彻底克服心理障碍，实现从恐惧开口到“流利开口”的转变。(Confidence)": "心理的な壁を完全に克服し、「流暢な会話」へと転換します。(Confidence)",
            "行动转化": "アクションへの移行",
            "学会不仅在现场聊得来，更能持续维系高价值关系。(Action)": "価値の高い関係を継続的に維持する方法を学びます。(Action)",
            "顺畅融入": "スムーズな統合",
            "掌握狮城沟通底色，实现文化丝滑嵌入，本地游刃有余。(Integration)": "シンガポールでのコミュニケーションの基本をマスターします。(Integration)",
            "归属共鸣": "帰属感と共感",
            "加入志同道合全球社群，拥有长期的支持系统。(Belonging)": "志を同じくするグローバルなコミュニティに参加します。(Belonging)",
            "课程适合谁？": "対象者は？",
            "五大基础场景 (初级)": "5つの基本シナリオ",
            "五大进阶场景 (中级)": "5つの高度シナリオ",
            "会议沟通不顺畅，难以清晰表达观点": "会議での発言が難しく、意見を明確に表現できない。",
            "邮件写作不够专业，影响职场形象": "メールの書き方が専門的でなく、職場での印象に影響する。",
            "面对电话沟通时缺乏信心": "電話でのコミュニケーションに自信がない。",
            "在社交聚会中不知如何自然展开对话": "ソーシャルな集まりで自然に会話を始める方法がわからない。",
            "演讲与汇报表现单一，缺乏吸引力": "プレゼンや報告の表現が単調で、魅力に欠ける。",
            "跨文化交流中容易产生沟通误差": "異文化コミュニケーションで誤解が生じやすい。",
            "商务谈判中的表达力度与说服力不足": "ビジネス交渉での表現力や説得力が不足している。",
            "团队合作场景下的沟通协同有待提升": "チームワークにおける協力とコミュニケーションの向上が必要。",
            "品牌叙事与价值传达能力较弱": "ブランドのストーリーテリングと価値の伝達能力が弱い。",
            "正式商务场合中的回应不够准确得体": "公式なビジネスの場での対応が正確かつ適切でない。",
            "不止于课堂": "教室を超えて",
            "除了商务课程，我们每月还会安排": "ビジネスコースに加え、毎月",
            " 场精选活动": "回の厳選されたイベント:",
            "行业分享会": "業界インサイト",
            "本地专业人士为您带来一手的行业洞察。": "現地の専門家が最新の業界インサイトを提供します。",
            "商务社交与人脉拓展": "ビジネスネットワーキング",
            "轻松愉悦的环境中结识更多商业伙伴。": "リラックスした雰囲気の中で、ビジネスパートナーと出会いましょう。",
            "真实场景体验": "リアルシナリオ体験",
            "走进新加坡真实商业与社交场景，提升实际沟通能力。": "実際のビジネスシーンに参加し、実践的なコミュニケーション能力を高めます。",
            "准备好开启您的成长之旅了吗？": "成長の旅を始める準備はできましたか？",
            "抓住在这个多元且国际化的商业环境中脱颖而出的机会。": "多様で国際的なビジネス環境の中で際立つ機会を掴みましょう。",
            "课程费用": "コース料金",
            "时长：3个月 (20次精品课)": "期間：3ヶ月（全20回）",
            "报名咨询 / 立即加入": "相談 / 今すぐ参加する",
            "成长型": "成長型"
        }
    },
    {
        "file": "index-zh.html",
        "lang_code": "zh-SG",
        "lang_name": "中文",
        "map": {}
    },
    {
        "file": "index-it.html",
        "lang_code": "it",
        "lang_name": "Italiano",
        "map": {
            "ULC Professionals Club | 跨国商务人士成长": "ULC Professionals Club | Crescita per Professionisti",
            "专为跨国商务人士打造的成长型课程项目。这是一次对自己成长的投资，对自己视野的拓展。": "Un programma di crescita per professionisti internazionali. Un investimento su te stesso e un'espansione dei tuoi orizzonti.",
            "核心优势": "Vantaggi Principali",
            "课程详情": "Dettagli del Corso",
            "适合人群": "Destinatari",
            "立即报名": "Iscriviti Ora",
            "这是一次对自己成长的投资，这是一次对自己视野的拓展": "Un investimento sulla tua crescita, un'espansione dei tuoi orizzonti",
            "专为跨国商务人士打造的 ": "Un Programma per ",
            " 课程项目": " Professionisti Internazionali",
            "这不只是英语学习，更是一个帮助你走进真实新加坡商务与社交圈的成长机会。": "Non solo inglese, ma un'opportunità per entrare nei veri circoli d'affari e sociali di Singapore.",
            "个月时长": "Mesi",
            "次精品课程": "Sessioni Premium",
            "真实社交融入": "Vera Integrazione Sociale",
            "了解详情及费用": "Scopri di più e Prezzi",
            "课程核心优势": "Vantaggi Principali del Corso",
            "独创的教学与实战结合模式，助你全方位提升跨国商务能力。": "Un modello originale che unisce insegnamento e pratica per migliorare le tue competenze aziendali a livello globale.",
            "沉浸式商业场域": "Ambiente Aziendale Immersivo",
            "在3个月、20次的多国家学员学习互动中，精准模拟真实商务与社交环境，让成长在实战中自然发生。(Immersive Practice)": "Simuliamo ambienti d'affari reali attraverso l'interazione con studenti internazionali. (Immersive Practice)",
            "结果导向型交付": "Orientamento ai Risultati",
            "坚持“每课必有产出”。通过可视化的成果转换 (Visible Output)，确保从理论输入到实操运用的无缝衔接。(Result-Oriented Delivery)": "Garantiamo un output visibile in ogni lezione, per passare dalla teoria alla pratica senza sforzo. (Result-Oriented Delivery)",
            "深度本地化解码": "Profonda Integrazione Locale",
            "专为非母语人士定制。不仅是语言的进阶，更是对新加坡规则与社交逻辑的深度拆解，助你跨越文化隔阂。(Deep Local Integration)": "Pensato per chi non è madrelingua per decodificare la cultura e superare le barriere a Singapore. (Deep Local Integration)",
            "跨文化深度链接": "Connessione Interculturale",
            "在多国背景的圈层中，建立能够共鸣、互信的高质量商业人脉网络，拓展国际化视野。(Cross-Cultural Connection)": "Costruisci reti commerciali di fiducia in un contesto interculturale. (Cross-Cultural Connection)",
            "开课时间：": "Data di Inizio:",
            "2026年4月21日 - 6月25日": "21 Apr - 25 Giu 2026",
            "上课频次：": "Frequenza:",
            "每周二、周四上课 (晚上 7:00 - 9:00)": "Ogni Mar e Gio (19:00 - 21:00)",
            "课程总量：": "Totale Sessioni:",
            "共 20 节课程": "20 Sessioni",
            "教学模式：": "Modalità di Insegnamento:",
            "以讨论式教学为主，结合真实场景与引导式交流": "Insegnamento basato sulla discussione con scenari reali e interazioni guidate.",
            "三个月进阶路径清晰": "Percorso di Crescita di 3 Mesi",
            "个人成长数字档案": "Profilo di Crescita Digitale",
            "商业实战挑战赛": "Sfida Aziendale Reale",
            "模块化技能产出": "Output di Competenze",
            "菁英结业荣誉包": "Kit di Diploma d'Élite",
            "关键收获": "Risultati Chiave",
            "三个月后，你将实现蜕变": "In 3 mesi, raggiungerai una trasformazione.",
            "英文表达重塑": "Rimodellazione dell'Inglese",
            "彻底克服心理障碍，实现从恐惧开口到“流利开口”的转变。(Confidence)": "Supera la paura di parlare e diventa fluente. (Confidence)",
            "行动转化": "Traduzione in Azione",
            "学会不仅在现场聊得来，更能持续维系高价值关系。(Action)": "Impara a mantenere relazioni di alto valore a lungo termine. (Action)",
            "顺畅融入": "Integrazione Fluida",
            "掌握狮城沟通底色，实现文化丝滑嵌入，本地游刃有余。(Integration)": "Padroneggia la comunicazione locale a Singapore. (Integration)",
            "归属共鸣": "Senso di Appartenenza",
            "加入志同道合全球社群，拥有长期的支持系统。(Belonging)": "Unisciti a una comunità globale per un supporto continuo. (Belonging)",
            "课程适合谁？": "Per Chì È Il Corso?",
            "五大基础场景 (初级)": "5 Scenari di Base",
            "五大进阶场景 (中级)": "5 Scenari Avanzati",
            "会议沟通不顺畅，难以清晰表达观点": "Difficoltà nell'esprimere chiaramente le opinioni durante le riunioni.",
            "邮件写作不够专业，影响职场形象": "Scrittura di e-mail non professionale che compromette l'immagine.",
            "面对电话沟通时缺乏信心": "Mancanza di fiducia nelle comunicazioni telefoniche.",
            "在社交聚会中不知如何自然展开对话": "Non sapere come conversare naturalmente agli eventi sociali.",
            "演讲与汇报表现单一，缺乏吸引力": "Presentazioni monotone e prive di attrattiva.",
            "跨文化交流中容易产生沟通误差": "Frequenti malintesi nelle comunicazioni interculturali.",
            "商务谈判中的表达力度与说服力不足": "Assenza di persuasione e forza espressiva nelle negoziazioni.",
            "团队合作场景下的沟通协同有待提升": "Necessità di migliorare collaborazione e interazione nel lavoro di squadra.",
            "品牌叙事与价值传达能力较弱": "Poca abilità nel trasmettere il valore del brand e storytelling.",
            "正式商务场合中的回应不够准确得体": "Risposte inadeguate in contesti aziendali formali.",
            "不止于课堂": "Oltre la Classe",
            "除了商务课程，我们每月还会安排": "Oltre ai corsi aziendali, organizziamo",
            " 场精选活动": " eventi selezionati al mese",
            "行业分享会": "Sessioni di Condivisione Settoriale",
            "本地专业人士为您带来一手的行业洞察。": "I professionisti locali offrono approfondimenti diretti.",
            "商务社交与人脉拓展": "Networking Aziendale",
            "轻松愉悦的环境中结识更多商业伙伴。": "Incontra partner d'affari in un ambiente rilassato.",
            "真实场景体验": "Esperienza in Scenari Reali",
            "走进新加坡真实商业与社交场景，提升实际沟通能力。": "Entra nel vivo del business e del social a Singapore per migliorare la comunicazione pratica.",
            "准备好开启您的成长之旅了吗？": "Pronto per il tuo viaggio di crescita?",
            "抓住在这个多元且国际化的商业环境中脱颖惊而出的机会。": "Cogli l'opportunità di distinguerti in un ambiente interculturale.",
            "抓住在这个多元且国际化的商业环境中脱颖而出的机会。": "Cogli l'opportunità di distinguerti in questo ecosistema dinamico.",
            "课程费用": "Costo del Corso",
            "时长：3个月 (20次精品课)": "Durata: 3 Mesi (20 Sessioni)",
            "报名咨询 / 立即加入": "Richiedi Info / Iscriviti Ora",
            "成长型": "Crescita"
        }
    },
    {
        "file": "index-de.html",
        "lang_code": "de",
        "lang_name": "Deutsch",
        "map": {
            "ULC Professionals Club | 跨国商务人士成长": "ULC Professionals Club | Wachstum für Profis",
            "专为跨国商务人士打造的成长型课程项目。这是一次对自己成长的投资，对自己视野的拓展。": "Ein wachstumsorientiertes Programm für internationale Geschäftsleute. Eine Investition in Sie selbst und Ihre Perspektiven.",
            "核心优势": "Kernvorteile",
            "课程详情": "Kursdetails",
            "适合人群": "Zielgruppe",
            "立即报名": "Jetzt anmelden",
            "这是一次对自己成长的投资，这是一次对自己视野的拓展": "Eine Investition in Ihre Entwicklung",
            "专为跨国商务人士打造的 ": "Ein ",
            " 课程项目": " Programm für Profis",
            "这不只是英语学习，更是一个帮助你走进真实新加坡商务与社交圈的成长机会。": "Nicht nur Englischlernen, sondern auch ein Einstieg in Singapurs reale Geschäftskreise.",
            "个月时长": "Monate",
            "次精品课程": "Premium-Sitzungen",
            "真实社交融入": "Echte soziale Integration",
            "了解详情及费用": "Mehr erfahren & Preise",
            "课程核心优势": "Zentrale Kursvorteile",
            "独创的教学与实战结合模式，助你全方位提升跨国商务能力。": "Ein exklusives Modell aus Theorie und Praxis, um Ihre internationalen Geschäftskompetenzen zu steigern.",
            "沉浸式商业场域": "Immersives Geschäftsumfeld",
            "在3个月、20次的多国家学员学习互动中，精准模拟真实商务与社交环境，让成长在实战中自然发生。(Immersive Practice)": "Wir simulieren reale Geschäftsszenarien in internationalen Gruppen für ein schnelles Wachstum. (Immersive Practice)",
            "结果导向型交付": "Ergebnisorientierter Ansatz",
            "坚持“每课必有产出”。通过可视化的成果转换 (Visible Output)，确保从理论输入到实操运用的无缝衔接。(Result-Oriented Delivery)": "Sichtbarer Output in jeder Sitzung für einen nahtlosen Übergang von Theorie zur Praxis. (Result-Oriented Delivery)",
            "深度本地化解码": "Lokale Integration",
            "专为非母语人士定制。不仅是语言的进阶，更是对新加坡规则与社交逻辑的深度拆解，助你跨越文化隔阂。(Deep Local Integration)": "Speziell für Nicht-Muttersprachler, um Singapurs Regeln und Kultur zu meistern. (Deep Local Integration)",
            "跨文化深度链接": "Interkulturelle Vernetzung",
            "在多国背景的圈层中，建立能够共鸣、互信的高质量商业人脉网络，拓展国际化视野。(Cross-Cultural Connection)": "Bauen Sie ein starkes internationales Netzwerk auf. (Cross-Cultural Connection)",
            "开课时间：": "Startdatum:",
            "2026年4月21日 - 6月25日": "21. Apr. - 25. Jun. 2026",
            "上课频次：": "Häufigkeit:",
            "每周二、周四上课 (晚上 7:00 - 9:00)": "Di und Do (19:00 - 21:00)",
            "课程总量：": "Anzahl der Sitzungen:",
            "共 20 节课程": "20 Sitzungen",
            "教学模式：": "Lehrmethode:",
            "以讨论式教学为主，结合真实场景与引导式交流": "Diskussionsbasiert, mit echten Szenarien und angeleitetem Austausch.",
            "三个月进阶路径清晰": "Klarer 3-Monats-Pfad",
            "个人成长数字档案": "Digitales Profil",
            "商业实战挑战赛": "Reale Business-Challenge",
            "模块化技能产出": "Sichtbare Ergebnisse",
            "菁英结业荣誉包": "Elite-Zertifikatskit",
            "关键收获": "Wichtigste Ziele",
            "三个月后，你将实现蜕变": "In 3 Monaten werden Sie sich transformieren.",
            "英文表达重塑": "Neuerfindung des Englischs",
            "彻底克服心理障碍，实现从恐惧开口到“流利开口”的转变。(Confidence)": "Überwinden Sie Sprachängste und gewinnen Sie Sicherheit. (Confidence)",
            "行动转化": "Aktion",
            "学会不仅在现场聊得来，更能持续维系高价值关系。(Action)": "Lernen Sie, langfristige wertvolle Beziehungen zu pflegen. (Action)",
            "顺畅融入": "Nahtlose Integration",
            "掌握狮城沟通底色，实现文化丝滑嵌入，本地游刃有余。(Integration)": "Meistern Sie Singapurs Kommunikationsregeln reibungslos. (Integration)",
            "归属共鸣": "Zugehörigkeitsgefühl",
            "加入志同道合全球社群，拥有长期的支持系统。(Belonging)": "Treten Sie einer globalen unterstützenden Community bei. (Belonging)",
            "课程适合谁？": "Zielgruppe des Kurses",
            "五大基础场景 (初级)": "5 grundlegende Szenarien",
            "五大进阶场景 (中级)": "5 fortgeschrittene Szenarien",
            "会议沟通不顺畅，难以清晰表达观点": "Probleme bei der Artikulation in Meetings.",
            "邮件写作不够专业，影响职场形象": "Unprofessionelle E-Mails, die das Image beeinträchtigen.",
            "面对电话沟通时缺乏信心": "Mangelndes Vertrauen bei Telefongesprächen.",
            "在社交聚会中不知如何自然展开对话": "Unsicherheit beim Starten von Gesprächen auf Netzwerktreffen.",
            "演讲与汇报表现单一，缺乏吸引力": "Monotone und wenig überzeugende Präsentationen.",
            "跨文化交流中容易产生沟通误差": "Fehlkommunikation durch interkulturelle Missverständnisse.",
            "商务谈判中的表达力度与说服力不足": "Schwache Überzeugungskraft in Geschäftsverhandlungen.",
            "团队合作场景下的沟通协同有待提升": "Verbesserungsbedarf bei Zusammenarbeit und Kommunikation.",
            "品牌叙事与价值传达能力较弱": "Schwächen in Marken-Storytelling und Wertvermittlung.",
            "正式商务场合中的回应不够准确得体": "Unangemessene Reaktionen bei formellen Geschäftsereignissen.",
            "不止于课堂": "Mehr als nur Unterricht",
            "除了商务课程，我们每月还会安排": "Darüber hinaus bieten wir monatlich",
            " 场精选活动": " ausgewählte Events:",
            "行业分享会": "Branchen-Insights",
            "本地专业人士为您带来一手的行业洞察。": "Lokale Experten teilen aktuelles Branchenwissen.",
            "商务社交与人脉拓展": "Business Networking",
            "轻松愉悦的环境中结识更多商业伙伴。": "Treffen Sie Partner in entspannter Atmosphäre.",
            "真实场景体验": "Echte Szenarienerprobung",
            "走进新加坡真实商业与社交场景，提升实际沟通能力。": "Praktische Kommunikation in Singapurs realer Geschäftswelt.",
            "准备好开启您的成长之旅了吗？": "Bereit für Ihre persönliche Entwicklung?",
            "抓住在这个多元且国际化的商业环境中脱颖惊而出的机会。": "Nutzen Sie die Chance, sich in einem internationalen Umfeld zu profilieren.",
            "抓住在这个多元且国际化的商业环境中脱颖而出的机会。": "Nutzen Sie die Chance, sich in einem internationalen Umfeld zu profilieren.",
            "课程费用": "Kursgebühr",
            "时长：3个月 (20次精品课)": "Dauer: 3 Monate (20 Sitzungen)",
            "报名咨询 / 立即加入": "Anfrage / Jetzt beitreten",
            "成长型": "Wachstumsorientiertes"
        }
    }
]

for locale in locales:
    output = base
    # Language attribute
    output = output.replace('lang="zh-SG"', 'lang="' + locale["lang_code"] + '"')
    
    # Text replacements using dictionary reverse-sorted by length to prevent partial matches
    sorted_keys = sorted(locale["map"].keys(), key=len, reverse=True)
    for zh in sorted_keys:
        output = output.replace(zh, locale["map"][zh])
    
    # Dropdown html creation
    all_langs = [("index.html", "English"), ("index-zh.html", "中文"), ("index-ko.html", "한국어"), ("index-ja.html", "日本語"), ("index-it.html", "Italiano"), ("index-de.html", "Deutsch")]
    current_lang_str = locale["lang_name"]
    
    dropdown_html_others = ""
    for u, txt in all_langs:
        if txt == current_lang_str:
            continue
        dropdown_html_others += '                            <a href="' + u + '">' + txt + '</a>\n'
    
    # Replacing the language button text in base
    output = re.sub(
        r'<button class="lang-btn"><i class="fa-solid fa-globe"></i> 中文 <i',
        '<button class="lang-btn"><i class="fa-solid fa-globe"></i> ' + current_lang_str + ' <i',
        output
    )
    
    # Replace the dropdown lines
    dropdown_regex = re.compile(r'<div class="lang-dropdown">([\s\S]*?)</div>')
    new_dropdown = '<div class="lang-dropdown">\n' + dropdown_html_others + '                        </div>'
    output = dropdown_regex.sub(new_dropdown, output)
    
    with codecs.open(r'c:\Users\PC\.gemini\antigravity\scratch\ulc_club_website\\' + locale["file"], 'w', 'utf-8') as fw:
        fw.write(output)

print("Generated HTML versions successfully.")
